package: fdns
source: fdns
version: '1:0.0.5'
architecture:
  - amd64
  - arm64
maintainer: DewepOnline <deb@dewep.online>
homepage: https://www.dewep.online/products/fdns
description:
  - Filter DNS
section: web
priority: optional
control:
  depends:
    - systemd
    - ca-certificates
    - sqlite3
  build: scripts/build.sh
  conffiles:
    - /etc/fdns/config.yaml
    - /var/lib/fdns/data.sqlite
  preinst: scripts/preinst.sh
  postinst: scripts/postinst.sh
  prerm: scripts/prerm.sh
  postrm: scripts/postrm.sh
data:
  usr/bin/fdns: build/bin/fdns_%arch%
  etc/fdns/config.yaml: configs/config.yaml
  etc/systemd/system/fdns.service: init/systemd/fdns.service
