env: dev
log: /dev/stdout

server:
  tcp: 0.0.0.0:10053
  http: 0.0.0.0:10080

blackholeip: 127.0.0.1
blacklistip:
  - 127.0.0.1
  - 10.0.0.0/24

dns:
  - 1.1.1.1
  - '1.0.0.1:53'
  - '2606:4700:4700::1111'
  - '[2606:4700:4700::1001]:53'

rules:
  - rule: example-ns.com
    type: dns
    ip4: 8.8.8.8
    ip6: '[2001:4860:4860::8888]:53'

  - rule: example.com
    type: none
    ip4: 10.0.0.1

  - rule: test.com
    type: none
    ip4: 10.0.0.1
    ip6: '::1'

  - rule: demo.com
    type: none

  - rule: '.*\.demo\.com'
    type: regexp
    ip4: 10.0.0.1

  - rule: '(\d+)-(\d+)-(\d+)-(\d+)\.example\.com'
    type: regexp
    ip4: '$1.$2.$3.$4'

  - rule: 'ex?mple.*'
    type: query
    ip4: 10.0.0.1