env: dev

log: /var/log/fdns.log
level: 3

http:
  addr: 0.0.0.0:10053
debug:
  addr: 0.0.0.0:12053

srv:
  enable: true
  addr: 0.0.0.0:53
dot:
  enable: false
  addr: 0.0.0.0:853
  cert:
    public: /etc/ssl/certs/fdns/public.pem
    private: /etc/ssl/certs/fdns/private.pem

middleware:
  throttling: 300

blacklistip:
  - 127.0.0.1
  - 10.0.0.0/24

sqlite:
  - file: /var/lib/fdns/data.sqlite

adblock-rules: https://fdns.dewep.online/adblock-rules.json
