env: dev

log: /dev/stdout
level: 3

http:
  addr: 0.0.0.0:10080
debug:
  addr: 0.0.0.0:10081

srv:
  enable: true
  addr: 0.0.0.0:8053
dot:
  enable: false
  addr: 0.0.0.0:8853
  cert:
    public: ./public.pem
    private: ./private.pem

middleware:
  throttling: 300

blacklistip:
  - 127.0.0.1
  - 10.0.0.0/24

sqlite:
  - file: ./data.sqlite

adblock-rules: https://fdns.dewep.online/adblock-rules.json
